services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'transito'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - /home/wagner/Documentos/estudos/algaworks/resources:/var/lib/mysql
